# Generated by Django 6.0 on 2025-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The user's question", max_length=255)),
                ('answer', models.TextField(help_text='The corresponding answer')),
            ],
        ),
    ]
